import streamlit as st
import smtplib

from email.mime.text import MIMEText 
from email.mime.multipart import MIMEMultipart 
port = 2525 
smtp_server = "smtp.mailtrap.io" 
login = "1a2b3c4d5e6f7g" # paste your login generated by Mailtrap 
password = "1a2b3c4d5e6f7g" # paste your password generated by Mailtrap
sender_email = "mailtrap@example.com" 
receiver_email = "new@example.com" 
message = MIMEMultipart("alternative") 
message["Subject"] = "multipart test" 
message["From"] = sender_email 
message["To"] = receiver_email 
# write the plain text part text = """\ Hi, Check out our new post on sending emails with Python! """ 
# write the HTML part html = """\ <html> <body> <p>Hi,<br> Check out our new post on sending emails with Python!</p> </body> </html> """
# convert both parts to MIMEText objects and add them to the MIMEMultipart message 
part1 = MIMEText(text, "plain") 
part2 = MIMEText(html, "html") 
message.attach(part1)
message.attach(part2) 
# send your email with smtplib.SMTP("smtp.mailtrap.io", 2525) as server: server.login(login, password) 
server.sendmail( sender_email, receiver_email, message.as_string() ) 
print('Sent')

st.title('MODELOS DE EMAIL')
col1, col2, col3 = st.columns([3, 3, 3])
col1.write('Atenção: Aviso de Veículos Desatualizados')
col1.code('''
    ***Atenção: Aviso de Veículos Desatualizados***

    Veículos Desatualizados:
    Prezado cliente, segue a lista de 3 veículo(s) sem atualização há pelo menos 96 horas.

    A desatualização de veículos pode ser ocasionada pelos motivos abaixo:

    Fora da cobertura de GSM (celular)
    Desligado desde a ultima atualização
    Em manutenção.
    Equipamento com problema.

    Caso o seu veículo não esteja em nenhuma das 3 primeiras situações, entre em contato pelo telefone (31) 2535-6060 [ ON SIG RASTREAMENTO ] solicitando uma verificação do equipamento.
    ''')

col2.write('Contato sem sucesso.')
col2.code('''
    ***Atenção: Aviso de Veículos Desatualizados***

    Veículos Desatualizados:
    Prezado cliente, segue a lista de 3 veículo(s) sem atualização há pelo menos 96 horas.

    A desatualização de veículos pode ser ocasionada pelos motivos abaixo:

    Fora da cobertura de GSM (celular)
    Desligado desde a ultima atualização
    Em manutenção.
    Equipamento com problema.

    Caso o seu veículo não esteja em nenhuma das 3 primeiras situações, entre em contato pelo telefone (31) 2535-6060 [ ON SIG RASTREAMENTO ] solicitando uma verificação do equipamento.
    ''')
